# Generated by Django 5.2.5 on 2025-08-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_auteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_couverture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
